language: node_js
node_js:
- "10.8"
- "8.12"
env:
global:
- export NODE_ENV=test
dist: trusty
services:
- postgresql
before_script:
- psql -c"create user kells with password 'kells60';" -U postgres
- psql -c "create database sendit_testdb;" -U postgres
- npm install
script:
- npm test
after_success: npm run coverage